jrl-umi3218/jrl-cmakemodules

idl.cmake

Client implementation generated by omniidl command were not suited for installation. This commit adds:
- generated files go into a path suitable for installation;
- generated `#include` preprocessor commands take these paths into account.

Add support for paths in GENERATE_IDL_FILE.

---

pkg-config.cmake

This macro may help CUDA users forward flags to `CUDA_ADD_*` macros.
Indeed, `SET_TARGET_PROPERTIES` does not work on CUDA libraries or
executables, so `PKG_CONFIG_USE_COMPILE_DEPENDENCY` cannot be used,
and the compiler options need to be given directly to the `CUDA_ADD_*`
macro (the other option is to modify `CUDA_{C/CXX}_FLAGS`...).
```cmake
PKG_CONFIG_ADD_COMPILE_OPTIONS(${LIB_NAME}_OPTIONS my-dependency)
CUDA_ADD_LIBRARY(${LIB_NAME} ${LIB_SRC} SHARED OPTIONS ${${LIB_NAME}_OPTIONS})
```
Any ideas on how to solve this problem in a cleaner way are of course welcome.

Add a PKG_CONFIG_ADD_COMPILE_OPTIONS macro.

---

doxygen.cmake

Hi,
This PR is related to #68. Namely it falls back to MathJax generation if latex, dvips and/or gs are not found.
Additonnaly, the doc target is also skipped altogether if Doxygen is not found.
I have also removed the dependency to Perl. It can be used in conjunction with Doxygen but it seems that we disable this in the default Doxygen file, hence the dependency should be introduced on a project by project basis.
Cheers

Improve doc target

---

shared-library.cmake

There is an issue when CMAKE_LINKER does not exist (happen on travis - 12.04 LTS /precise), it makes the  [REGEXP test fails](https://github.com/jrl-umi3218/jrl-cmakemodules/blob/master/shared-library.cmake#L35). This pull request fixes it by calling CMakeFindBinUtils if the variables is not set.

[shared-library] Find CMAKE_LINKER if the variable does not exist.

---

doxygen.cmake
doxygen/Doxyfile.in

As mentioned in the Doxygen manual (http://www.stack.nl/~dimitri/doxygen/manual/customize.html#minor_tweaks_header_css), the style sheet should not be passed with `HTML_STYLESHEET` but with `HTML_EXTRA_STYLESHEET`. Tag `HTML_STYLESHEET` produces conflicts between Doxygen versions.
To ensure backward compatibility, variable `DOXYGEN_USE_TEMPLATE_CSS` is introduced. When set to `TRUE`, the default Doxygen CSS is used instead of the one provided by this module (outdated on Ubuntu 14.04).
The variable defaults to `YES` and users willing to have backward compatibility should add `SET (DOXYGEN_USE_TEMPLATE_CSS NO)` to `CmakeLists.txt`.
A cleaner solution would be to replace in `doxygen/Doxyfile.in` this line:
```HTML_STYLESHEET        = @PROJECT_BINARY_DIR@/doc/doxygen.css```
by …

Doxygen stylesheet

---

header.cmake

As the original comment explains, that header should not be installed (this is **not** `config.hh`):
```cmake
```
This behavior was introduced in de268ce19d0526f6364ad60ecafc2bfeb7c77b72.

header.cmake: do not install config.h

---

eigen.cmake

As @francois-keith pointed out [here](https://github.com/roboptim/roboptim-core/pull/110#discussion_r61175686), using `SEARCH_FOR_EIGEN` does not add Eigen as a required dependency in the generated `${PROJECT_NAME}.pc` if the pkg-config lookup was used, and it does not add the include directory to the `CFLAGS` if the "manual" search was used. This PR is an attempt to solve both these issues.
@aescande could you test this on Windows?

eigen.cmake: fix Eigen dependency in generated .pc

---

boost.cmake

On Apple system, boost_python has unresolved symbols and are resolved according to the Python interpreter version.
One has to use `TARGET_LINK_BOOST_PYTHON ` to properly links its application against boost_python.

Handle linking against boost_python on APPLE

---

pkg-config.cmake

This PR follows #100.
CMake does not automatically transform a LIST to a STRING concerning the COMPILE_OPTION. This cast must be done manually for old CMake versions.

Cast from LIST to STRING - mandatory for old CMake version

---

boost.cmake

This PR prevents the warning message to be displayed for normal users.

[Boost] Use AUTHOR_WARNING for boost Python linkage macro

---

pkg-config.cmake

This avoids quoting cflags while building, see #106

 Check cmake version before casting list to string

---

Config.cmake.in
base.cmake
package-config.cmake
package.cmake

based on: https://github.com/forexample/package-example
This helps generate config files so other regular cmake packages can find and use library dependencies. For example a simple change to [RBDyn/src/CMakeLists.txt](https://github.com/jrl-umi3218/RBDyn/blob/master/src/CMakeLists.txt) will install the following:
```
-- /usr/local/lib/cmake/RBDyn/RBDynConfig.cmake
-- /usr/local/lib/cmake/RBDyn/RBDynConfigVersion.cmake
-- /usr/local/lib/cmake/RBDyn/RBDynTargets.cmake
-- /usr/local/lib/cmake/RBDyn/RBDynTargets-noconfig.cmake
```
That way a call to find_package(RBDyn) will automatically be configured!
Here is an example change to [RBDyn/src/CMakeLists.txt](https://github.com/jrl-umi3218/RBDyn/blob/master/src/CMakeLists.txt), which I will submit separately once this is merged:
``` cmake …
```

Can now generate standard CMake *Config.cmake and *Version.cmake files.

---

doxygen.cmake

This PR is a follow-up to #72 
This makes doc dependent on the generation of doxygen template CSS. Otherwise, the custom command is not run and the generated documentation does not have its stylesheet.

Create a dependency between template CSS creation and doc target

---

config.h.cmake
config.hh.cmake
deprecated.hh.cmake
warning.hh.cmake

This module generates a few header files with the GPL license. They are installed and therefore force dependencies to be GPL.
This pull-request changes the license to BSD-2.
@thomas-moulard : as the author of these files, if you agree, could you merge this PR ?

Change license of generated files from GPL / LGPL to BSD

---

.docs/conf.py
python.cmake

Sphinx version has been updated on [readthedoc.org](readthedoc.org) and some deprecated classes have been removed. See [this](http://www.sphinx-doc.org/en/master/changes.html#id37) and [this](http://www.sphinx-doc.org/en/master/changes.html#id18).

Fix compilation of documentation

---

boost.cmake

The warning was here to highlight the modification.
It seems now no more useful, and can lead to some confusions to common people who are not developers.

[Boost] Remove useless warning message

---

release.cmake

Hi,
I think that `make release` should also create the tarball, so I hereby suggest to add `make dist` inside it.
This is the purpose of this PR, plus updating the corresponding documentation.
Guilhem.

make release: also run make dist

---

release.cmake

This remove the current dist directory from the current build path after tar.gz generation

Update release procedure by adding distclean command

---

python.cmake

This new forcing is mandatory for recent versions of cmake >= 3.13.3

python: force version for PythonLibs

---

cmake_uninstall.cmake.in

I have noticed `make uninstall` can leave lots of `.pyc` files behind.
With this addition, when a `.py` file is removed the corresponding `.pyc` is also removed, if it exists.

[uninstall] remove .pyc files when needed

---

pkg-config.cmake

Hi,
I had the following error:
```
CMake Error: Error in cmake code at cmake/pkg-config.cmake:910:
Parse error.  Expected a newline, got identifier with text "SET".
CMake Error at cmake/base.cmake:98 (INCLUDE):
include could not find load file:
cmake/pkg-config.cmake
Call Stack (most recent call first):
CMakeLists.txt:3 (INCLUDE)
```

fix formatting errors

---

idl.cmake

as attribute '__doc__' of 'type' objects is not writable in Python 2

[IDL] enable docstrings only in Python 3

---

python.cmake

Hi,
This follows #214 and addresses https://github.com/jrl-umi3218/jrl-cmakemodules/pull/214#issuecomment-526846322, by allowing the packager to use [Python's standard PYTHON_SITELIB](https://docs.python.org/3/library/site.html) regardless of the architecture he is currently working on.
This is required to allow the packaging of Python 3 modules on robotpkg.

python: option for standard policy regardless of architecture

---

base.cmake
oscheck.cmake

I need to define first the CHECK_{DEBIAN,NETBSD,etc} first before including `INCLUDE(${CMAKE_CURRENT_LIST_DIR}/GNUInstallDirs.cmake)`

os: split in a separate file the definition of OS checker

---

pkg-config.cmake

...in accordance with cmake's documentation.
freedesktop [1] and perl [2] implementations of pkg-config differ
in the way they parse extra spaces in version constraints
(like eigen3 >= 3.0.5). See the following table for examples showing
how library names are parsed by the two implementations:
| input             | freedesktop     | perl            |
|-------------------|-----------------|-----------------|
|                   | 0.29.1          | 0.23026         |
| "eigen3 >= 3.0.5" | "eigen3"        | "eigen3"        |
| "eigen3>=3.0.5"   | "eigen3>=3.0.5" | "eigen3>=3.0.5" |
| "eigen3 >= 3.0.5" | "eigen3"        | "eigen3 "       |
cmake's FindPkgConfig.cmake documentation [3] advises
using pkg_check_modules without spaces around the operator.
Hence, one should do: …

PkgConfig: do not advise putting spaces around operators

---

github/update-doxygen-doc.sh

In some cases, dependencies in `GIT_DEPENDENCIES` may not generate a .pc file and that would choke that script, this commit fixes that.

Don't fail if the package has no pkg-config file

---

cmake_reinstall.cmake.in
cmake_uninstall.cmake.in
uninstall.cmake

Closes #298
This is implemented so that `make reinstall` is also working on the first time it's invoked or if the project has already been uninstalled.
For this to work correctly, `make uninstall` also removes the install manifest

Create reinstall target

---

boost.cmake

Having a warning to notify that we are reducing warning is still a warning after all. Jenkins considers warnings in CMake as unstable.

boost.cmake: Turn warning to status

---

package-config.cmake

Do not call INSTALL(EXPORT ...) when having no targets but generates the Config.cmake file.

Fix isssue #398

---

python.cmake

Hi,
This is just englobing the `PYTHON_SITELIB` computation in a guard, allowing the user to directly provide it. This was requested in https://github.com/Gepetto/example-robot-data/pull/38.
eg.
```bash
╰─>$ cmake -DCMAKE_INSTALL_PREFIX=/tmp/foo -DPYTHON_SITELIB=/tmp/bar ..
[…]
-- Found Python3: /usr/bin/python (found version "3.8.3") found components: Interpreter Development 
-- PythonLibraryDirs: /usr/lib
-- PythonLibVersionString: 3.8.3
-- Python site lib: /tmp/bar
```
(obviously, the site lib can also be inside the install prefix)

[Python] Allow user to provide PYTHON_SITELIB

---

python.cmake

Hi,
This might not be the best workaround, but I think this does the job.
I'm not sure what was the exact issue on windows that #392 had to fix, though.

[Python] allow compile_pyc from different directories, fix #425

---

find-external/CppAD/Findcppad.cmake
find-external/CppAD/Findcppadcg.cmake

As @nmansard found that `-Dcppadcg_PREFIX=…` didn't work as expected.

[find-external/cppad] Fix prefix hints

---

boost.cmake

because CMAKE_SOURCE_DIR is always defined while PROJECT_SOURCE_DIR
is only defined after `project` has been called.

Use CMAKE_SOURCE_DIR instead of PROJECT_SOURCE_DIR

---

package-config.cmake

Another fix after #449 : this one fix an issue about a `<project>/componentConfig.cmake.in` not found, while it is in `<project>/cmake/componentConfig.cmake.in`.

package-config: replace CMAKE_CURRENT_LIST_DIR by PROJECT_JRL_CMAKE_MODULE_DIR

---

distcheck.cmake

Otherwise, on a package that includes catkin, it tries to create a `CATKIN_TEST_RESULTS_DIR` which is inside the read-only directory, which fails.

distcheck: create a test results dir

---

find-external/OpenMP/FindOpenMP.cmake

It looks like the default script is not working correctly on MAC.

Add simple way to retrieve OpenMP

---

package-config.cmake

This PR uses the `CMAKE_INSTALL_LIBDIR` variable to install the CMake configuration files.
This should mostly affect packaging (ping @nim65s )

Use CMAKE_INSTALL_LIBDIR instead of lib for package config

---

release.cmake

Sed on OSX and BSD systems is different from Linux version.
I've adapted the sed regular expression to handle these systems.
@nim65s @jmirabel @wxmerkt Could you check on your side I did not break the behaviour on Linux systems?

Handle BSD sed when updating package.xml

---

test.cmake

This improves the integration with build tooling and CI systems including colcon and catkin_make_isolated. Without this target, the unit tests defined by the test macro cannot automatically be run with colcon/catkin_make_isolated tooling. Having this target enables us to activate full ROS-CI for CMake projects based on jrl-cmakemodules.(*)
(*) With a caveat of registration of projects from underlay workspaces that happens with some build tools such as colcon but not others such as catkin-tools that is yet to be resolved.

[test] Add custom target run_tests to run ctest

---

cxx-standard.cmake

Hi,
@jcarpent  noted that some messages could be broken, as they use `CMAKE_CXX_STANDARD`, which might not be defined. 
This PR adds a `_CURRENT_STANDARD` intermediate variable to fix this.
This also greatly symplify the way we check if the requested minimum is higher than the current one or not.

[cxx-standard] clean

---

_unittests/python/CMakeLists.txt
gtest/CMakeLists.txt.in

fix warnings like:
> CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
>   Compatibility with CMake < 2.8.12 will be removed from a future version of
>   CMake.
also ref. #338

update minimum required to 3.1

---

config.hh.cmake

Reverts jrl-umi3218/jrl-cmakemodules#504
Turns out I had only tested this with its use in C++ code, but not in macros (`#if HPP_FCL_VERSION_AT_LEAST(1,1,1)`). We can't cast as a macro, hence the revert.

Revert "config: Avoid type-limits warning by performing signed comparison"

---

version-script.cmake

In some systems (e.g. windows), the cmake version string looks like this `3.17.20032601-MSVC_2`. This causes the check `if(${CMAKE_VERSION} VERSION_GREATER 3.17.6)` to return true, and then cmake fails (because `CheckLinkerFlag` does not exist). This PR does the opposite check `VERSION_LESS` (since `VERSION_GREAT_OR_EQUAL` does not exist). This is affecting my `SpaceVecAlg` and `RBDyn` builds.

Fix for weird CMake versions

---

python.cmake

Hi,
In many places, we need only the Python interpreter (and sometimes the include dirs), but libpythonX.Y.so is not necessary.
Building wheel packages allowing distribution on [PyPI](https://pypi.org) even explicitly forbids it (ref. [PEP513](https://peps.python.org/pep-0513/#libpythonx-y-so-1)). Therefore, it is not available on the [manylinux](https://github.com/pypa/manylinux) distribution.
Building jrl-cmakemodules packages on that distribution is currently not working, because CMake consider the `Development` component not found when `libpythonX.Y.so` is not available.
So I think we need to remove that.
Maybe this is required in some other cases I didn't think about yet, so an opt-out option would be better than just this blunt removal. Any idea about that ?

python: Development might not be required

---

doxygen.cmake

Hi,
I'm not sure how this went unnoticed, but in many of our projects, documentation from *.hpp files is not generated, eg:
https://gepettoweb.laas.fr/doc/stack-of-tasks/tsid/master/doxygen-html/files.html
Here is a trivial fix.

add *.hpp to default DOXYGEN_FILE_PATTERNS

---

boost/FindBoost.cmake

One more quite common warning that doesn't require user action, reducing it to a status message.

FindBoost: Change 'no header defined' WARNING to STATUS

---

pyproject.py
release.cmake

Automatically set the version number in the `pyproject.toml` file, similar to what's done for the `package.xml` . This is useful for projects like [proxsuite](https://github.com/simple-robotics/proxsuite) that use [cmeel](https://github.com/cmake-wheel/cmeel).

Release: edit version number in pyproject.toml

---

cmake_uninstall.cmake.in
uninstall.cmake

This PR automatically calls `uninstall` before an install command is called.
- The motivation is to avoid keeping stale libraries and obsolete header files around
- This relies on the documented fact that `install` commands are run in the specified order, hence the "hook" is setup early, normally before any call to `install` in user code happened (i.e. as long as you don't have `install` commands before `include(base.cmake)` it should work
- it changes the behavior of the uninstall target so that it doesn't print an error message if called before install (for the first time)
Since it's an impactful change I will wait for feedback (@nim65s @jcarpent @wxmerkt in particular) before merging

Automatically uninstall before install

---

pyproject.py
release.cmake

Hi,
On projects with a `pyproject.toml` file without a `project` key with a `version` inside, `make release` is currently failing with:
```
╰─>$ make -sj3 release VERSION=4.0.10
Updating package.xml to 4.0.10
[devel 3f41a9f] release: Update package.xml version to 4.0.10
1 file changed, 1 insertion(+), 1 deletion(-)
Updated package.xml and committed
Updating pyproject.toml to 4.0.10
Traceback (most recent call last):
File "…/cmake/pyproject.py", line 24, in <module>
update_pyproject_version(sys.argv[1])
File "…/cmake/pyproject.py", line 17, in update_pyproject_version
doc["project"]["version"] = version
File "/usr/lib/python3.10/site-packages/tomlkit/container.py", line 650, in __getitem__
raise NonExistentKey(key)
tomlkit.exceptions.NonExistentKey: 'Key "project" does not exist.'
Please …
```

pyproject.py: check project / version exist

---

deprecated.hh.cmake

E.g. Pinocchio defines its own redundant `PINOCCHIO_PRAGMA`. This results in hundreds of warnings -- checking and only defining if required fixes this issue. Alternatively we could force undef here, but I don't think that's a good idea.

deprecated.hh.cmake: Only define PROJECT_PRAGMA if not yet defined

---

hpp/idl/omniidl_be_python_with_docstring.py

Hi,
Trying to release hpp-corbaserver, I got the following error:
```
omniidl: Could not import back-end 'omniidl_be_python_with_docstring'
omniidl: Maybe you need to use the -p option?
omniidl: (The error was 'No module named 'omniidl_be.omniidl_be_python_with_docstring'')
```
I have no idea why, but removing an unused import fixed the issue.
@jmirabel : you added this file in #194, so if you have a better understanding of the issue, or have a better idea, that's welcome. 
Otherwise, I think this change couldn't harm anyway, so we can just merge this and don't loose any time here.

hpp/idl: remove useless import

---

find-external/Simde/FindSimde.cmake

`REASON_FAILURE_MESSAGE` was only introduced in cmake v3.16.

FindSimde: use hint for failure only for cmake > 3.15

---

find-external/qpOASES/FindqpOASES.cmake

Make FindqpOASES compatible with other distros than linux
Adding other names with the other extensions possibles.
Best,
Yann

Make FindqpOASES compatible with other distros than linux

---

python.cmake

Hi, 
This add a guard in exported modules to avoid multiple ones calling successive findpython(), which can fail (for a yet unknown reason).
This is required when package A and B are independant and use and export findpython(), and package C depends on both.
eg. hpp-gepetto-viewer configuration fails, because its `add_project_dependency("hpp-corbaserver")` calls `findpython()`, and then `add_project_dependency("gepetto-viewer")` calls it again, and fail.

avoid multiple findpython() calls

---

base.cmake

Hi,
Looking at logs of many projects configuring at once is a bit hard because we never know which is the current one.
Here is a trivial helper for this case.

base: displaying which project is currently being configured

---

stubs.cmake

Supplying python bindings target name ensures stubgen doesn't import a target that's not built yet.
Before, stubgen used to check if a target named "python" existed. This PR allows the user to give a list of optional arguments, each of which are checked to be an existing target and then appended to the stubgen target's dependencies.
Resolves #584
This should also fix stack-of-tasks/pinocchio/issues/1879

stubs: allow user to supply name of dependent target to generate_stubs()

---

pkg-config.cmake

instead of hardcoding `../..`.
Specially useful for ROS which sets LIBDIR to `lib/x86_64-linux-gnu`
fix: https://github.com/humanoid-path-planner/hpp-fcl/issues/392
fix: https://github.com/stack-of-tasks/pinocchio/issues/1524 (2023 comments)

pkg-config: compute relative path to prefix

---

base.cmake
pkg-config.cmake
relpath.cmake

with `REL_INV_INSTALL_PATH(FILE VARIABLE)` to compute the relative inverse install path of `FILE` and store it into `VARIABLE`
eg:
```cmake
rel_inv_install_path("${CMAKE_INSTALL_LIBDIR}/pkgconfig" _PC_REL_INV_INSTALL_PATH)
set(_PKG_CONFIG_PREFIX "\${pcfiledir}/${_PC_REL_INV_INSTALL_PATH}")
```
and `LIB_REL_RPATH(TARGET_INSTALL_DIR VARIABLE)` to compute the relative path from this `TARGET_INSTALL_DIR` to `CMAKE_INSTALL_LIBDIR`."
eg:
```cmake
set(${PYWRAP}_INSTALL_DIR ${PYTHON_SITELIB}/${PROJECT_NAME})
if(UNIX)
lib_rel_rpath(${${PYWRAP}_INSTALL_DIR} ${PYWRAP}_INSTALL_RPATH)
set_target_properties(${PYWRAP} PROPERTIES INSTALL_RPATH "${${PYWRAP}_INSTALL_RPATH}")
endif()
install(TARGETS ${PYWRAP} DESTINATION ${${PYWRAP}_INSTALL_DIR})
```
fix. https://github.com/stack-of-tasks/eigenpy/issues/353 …

Add relpath.cmake

---

doxygen.cmake

_PKG_CONFIG_DOXYGENDOCDIR contained a non-existing path
The previous solution was producing an error of the form:
```bash
-- Doxygen rendering: using MathJax backend
CMake Error at cmake/doxygen.cmake:686 (file):
file RELATIVE_PATH must be passed a full path to the directory:
${pcfiledir}/../../share/doc/proxnlp/doxygen-html
Call Stack (most recent call first):
cmake/base.cmake:319 (_setup_project_documentation_finalize)
cmake/base.cmake:210 (setup_project_finalize)
CMakeLists.txt:9223372036854775807 (SETUP_PROJECT_FINALIZE_HOOK)
```

Fix relative path issues for doc

---

base.cmake

ref. https://cmake.org/cmake/help/latest/variable/ENV.html:
> To test whether an environment variable is defined, use the signature
> `if(DEFINED ENV{<name>})` of the `if()` command.

fix ENV syntax for set_default_cmake_build_type

---

python.cmake

Hi,
This allow compatibility with python 3.12, remove warnings on python 3.10 & 3.11, but break compatibility with python < 3.4 (for pathlib)
NB: I guess this would require multilple tests in different setups to check that this is not breaking anything.

python: remove distutils use, fix #623

---

boost/FindBoost.cmake

fix https://github.com/jrl-umi3218/jrl-cmakemodules/commit/ffd8d4441e62c9d4b48997acee03d43c3d98a3cb#diff-61fcbab488c8e9c131b5c70aab7aae76ddf3743bf5a26a72dd0130ac6ea93c94L632 introduced in https://github.com/jrl-umi3218/jrl-cmakemodules/pull/620
ref. https://github.com/stack-of-tasks/eigenpy/pull/394

findboost: fix logic

---

python.cmake

It was removed in https://github.com/jrl-umi3218/jrl-cmakemodules/pull/624, but ROS-CI still needs it.

bring python2 support back

---

release.cmake

Hi,
Eigenpy [recently adopted](https://github.com/stack-of-tasks/eigenpy/pull/396) a changelog style based on https://keepachangelog.com/.
Therefore, on each release, a few lines should be added / updated in this file, so I guess the right place to do so is in the `release` target, along with other similar file updates, like package.xml & pyproject.toml.
Here is a simple implementation in `sed`.
It would be problematic in projects:
1. using the jrl-cmakemodule
2. having a CHANGELOG.md
3. not following keepachangelog.com
4. with lines matching the regex `\#\# \\[Unreleased\\]` and/or `^\\[Unreleased]: \\(https://.*compare/\\)\\(v.*\\)...HEAD`
But I guess there those conditions are never met.
@jorisv : maybe you would like to test this on your side ?

release: update CHANGELOG.md

---

memorycheck_unit_test.cmake.in
test.cmake

ADD_PYTHON_MEMORYCHECK_UNIT_TEST macro run Python unit tests through valgrind to detect memory leaks.

Add ADD_PYTHON_MEMORYCHECK_UNIT_TEST macro

---

cxx-standard.cmake

Hi,
This PR fixes a corner case where:
- the variable `CMAKE_CXX_STANDARD` is not set
- the user calls the macro `CHECK_MINIMAL_CXX_STANDARD` with the `ENFORCE` option
- the compiler reports through the `__cplusplus` define that the compiler mode satisfies the C++ standard
Right now, the macro would print the line `C++ standard sufficient: Minimal required ..., currently defined ...`, which only corresponds to what it found regarding the compiler, but leaves `CMAKE_CXX_STANDARD` undefined even when ENFORCE is given.
The change in this PR ensures that, in this corner case, the macro call with the ENFORCE option sets `CMAKE_CXX_STANDARD`  to the detected compiler C++ standard.  
This is useful because the library developer might want to create CMake compile definitions, targets, etc. by …

Properly enforce (when asked) value of CMAKE_CXX_STANDARD when not set but C++ compiler reports right standard

---

test.cmake

PYTHONPATH computed by COMPUTE_PYTHONPATH need more extra back slash on Windows

Fix PYTHONPATH for CTEST on Windows

---

gtest/CMakeLists.txt.in
stubgen/CMakeLists.txt.in

Happy new year :)
This is to silence in eg. stubgen:
> CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
>   Compatibility with CMake < 3.5 will be removed from a future version of
>   CMake.
>
>   Update the VERSION argument <min> value or use a ...<max> suffix to tell
>   CMake that the project does not need compatibility with older versions.

bump various cmake_minimum_required

---

git-archive-all.sh

When creating a release, submodules in build directory (fetchcontent) are finded.
Instead of finding submodules with find, this PR use `git submodules status --recursive`.

Fix how submodules are found

---

compiler.cmake

This function allow to choose different compiler options or definitions based on the compiler frontend

Add CXX_FLAGS_BY_COMPILER_FRONTEND function

---

doxygen.cmake

Generating TAGFILES recursively results in low level dependencies to be duplicated many times in the variable.
This makes doxygen run for hours when compiling hpp-doc for example.
This PR removes duplicate entries.

[doxygen] Remove duplicate entries in TAGFILES variable.

---

cmake_reinstall.cmake.in
cmake_uninstall.cmake.in
uninstall.cmake

I encountered some issues on a computer where CMake is installed with a space inserted. using `@CMAKE_COMMAND@` instead of  `"@CMAKE_COMMAND@"` would create some problems. However, there's not much point in using `@CMAKE_COMMAND@` in the first place so I have replaced all usage with `${CMAKE_COMMAND}` which is correctly handled in the `execute_process` calls

Use ${CMAKE_COMMAND} instead of @CMAKE_COMMAND@ in generated scripts

---

CMakeLists.txt

Hi,
This follow #670, and fix the case where this project is used with `FetchContent`, because `FetchContent` would detect the new `CMakeLists.txt` and execute it.
Then, if this `CMakeLists.txt` includes `base.cmake`, multiple global targets are created in the `FetchContent` and an error is raised later, in the downstream `project()` initialization, as its own include of `base.cmake`  would try to define again the same global targets.
Of course, the proper fix would be to gracefully allow multiple inclusions of `base.cmake`, but that's a lot of work.
Instead, this PR only get what's need to generate CMake export in CMakeLists.txt.

CMakeLists.txt: dont include base

---

doxygen.cmake

Following #669, remove_duplicate might be called on en empty list, resulting with:
```cmake
CMake Error at cmake/doxygen.cmake:712 (remove_duplicates):
remove_duplicates Function invoked with incorrect arguments for function
named: REMOVE_DUPLICATES
Call Stack (most recent call first):
cmake/base.cmake:328 (_setup_project_documentation_finalize)
cmake/base.cmake:228 (setup_project_finalize)
CMakeLists.txt:9223372036854775807 (SETUP_PROJECT_FINALIZE_HOOK)

doxygen: fix remove_duplicate

---

CMakeLists.txt

Hi,
Since #670, when the jrl-cmakemodules is used with `FetchContent` in a project, the jrl-cmakemodules is installed with the project, which is usually not desirable.
This PR adds a simple guard to prevent that.

avoid installing when fetched

---

find-external/CoinUtils/FindCoinUtils.cmake

Hi,
This fix uses of clp when clp and coin-utils are not installed in the same prefix, because clp try to include "CoinPragma.hpp" from coin-utils while coin-utils export include/ as includedir and provide include/coin/CoinPragma.hpp.

find-external coin-utils: include coin subdir

---

memorycheck_unit_test.cmake.in
test.cmake

- Add a new function (`ADD_PYTHON_MEMORYCHECK_UNIT_TEST_V2`) to extend more easily the function API

Manage suppresion file when calling valgrind

---

find-external/GMP/FindGMP.cmake
find-external/MPFR/FindMPFR.cmake

- Use `IMPORTED_IMPLIB` instead of `IMPORTED_LOCATION` on Windows

Fix FindMPFR and FindGMP on Windows

---

header.cmake
test.cmake

Add a way to specify include dir in GENERATE_CONFIGURATION_HEADER.
Use modern cmake parameter parsing to avoid breaking the API in each change.

GENERATE_CONFIGURATION_HEADER_V2

---

base.cmake
coverage.cmake
debian.cmake
dist.cmake
distcheck.cmake
doxygen.cmake
package-config.cmake
python-helpers.cmake
release.cmake
sphinx.cmake
stubs.cmake
test.cmake
uninstall.cmake
version.cmake

This PR aims to allow project using jrl-cmakemodules to be used under the same root CMakeLists.txt (workspace).
- Use unique target name (prefixed by project name)
- Keep old target as aggregators
- Allow to deactivate the automatic call to setup_project_finialize (called in the workspace CMakeLists.txt instead of the project CMakeLists.txt)
- Reformat some custom_target
- `PROJECT_PACKAGES_IN_WORKSPACE` that should avoid running find_package in `ADD_PROJECT_DEPENDENCY` and `ADD_PROJECT_PRIVATE_DEPENDENCY` on project already in the workspace
- Add `ADD_PROJECT_PRIVATE_DEPENDENCY` that check for `PROJECT_PACKAGES_IN_WORKSPACE` before calling find_package
- Add `PROJECT_PYTHON_PACKAGES_IN_WORKSPACE` to include Python modules from workspace in `PYTHONPATH`
- Use `PROJECT_SOURCE_DIR` and …

Allow to create workspace

---

gtest.cmake

Switch to the main branch as default tag for GTEST

---

python.cmake

This is required for Numpy 2. See failure here https://github.com/conda-forge/eigenpy-feedstock/pull/139 for instance.

Look for Numpy to fill Python_NumPy_INCLUDE_DIR hint

---

find-external/CDD/FindCDD.cmake
find-external/CLP/FindCLP.cmake
find-external/CoinUtils/FindCoinUtils.cmake
find-external/glpk/Findglpk.cmake

find-external: remove suffix from library names

---

doxygen.cmake

It is already called during install step if `INSTALL_DOCUMENTATION` is set, except for MSVC.

exclude `${PROJECT_NAME}-doc` from `ALL`

---

CMakeLists.txt
base.cmake
ros2.cmake

This is a proposal to fix #716.
This PR introduces a new file ros2.cmake.
It provides a macro _install_project_ros2_ament_files to generate files for the ROS2 ament system.
This macro is called in setup_project_finalize() in base.cmake.
The generation works if the variable BUILDING_ROS2_PACKAGE is set (to TRUE
for instance).
pre-commit was run over the PR.
Tested against unittest.

ROS 2 file generation macro

---

find-external/Ipopt/FindIpopt.cmake

This PR:
- adds a FindIpopt.cmake module, which enables the use of `find_package(Ipopt)`

Add FindIpopt.cmake module

---

python.cmake

When PYTHON_SITELIB is not provided and is searched from python interpreter call, the path in not normalized and can contains `\`.
This create an error when calling `python_install_on_site` macro.

Remove Windows path separator in PYTHON_SITELIB

---

distcheck.cmake

This PR add two orthogonal features:
- Allow to use ninja for the distcheck target (and then, the release target)
- Allow to call distcheck from a Pixi environment

Allow to launch distcheck with Ninja and also add Pixi support

---

config.hh.cmake

With gcc < 13, mixing old `__attribute__` keyword and C++11 `[[ ]]` attribute can create some error.
To reproduce, we can compile the following code snippet on godbot:
```cpp
class [[gnu::visibility ("default")]] [[deprecated]] SomeClass1
{};
class [[gnu::visibility ("default"), deprecated]] SomeClass2
{};
class __attribute__((visibility ("default")))  __attribute__((deprecated)) SomeClass3
{};
class __attribute__((visibility ("default"))) [[deprecated]] SomeClass4
{};
int main()
{
SomeClass1 c1;
SomeClass2 c2;
SomeClass3 c3;
SomeClass4 c4;
}
```
`SomeClass4` will not compile on gcc < 13 with the following error:
```
<source>:10:47: error: expected identifier before '[' token
10 | class __attribute__((visibility ("default"))) [[deprecated]] SomeClass4
```
This code build well with clang …

Use c++11 attribute when C++11 is activated

---

config.hh.cmake

Reverts jrl-umi3218/jrl-cmakemodules#725
[[gnu::visibility]] is not working well for global variable:
```cpp
extern [[gnu::visibility("default")]] int GLOBAL; // not working
extern __attribute__((visibility("default"))) int GLOBAL; // working
```
So I revert it to avoid compatibility issue.
We finally found another solution in https://github.com/stack-of-tasks/pinocchio/pull/2469

Revert "Use c++11 attribute when C++11 is activated"

---

CMakeLists.txt
header.cmake
install-helpers.cmake
python-helpers.cmake

CMake install instruction support the [COMPONENT parameter](https://cmake.org/cmake/help/latest/command/install.html#id4) that allow to install some subpart of the package by doing `cmake -DCOMPONENT=<component_name> -P build/cmake_install.cmake`.
This will allow to more easily split our package into subpackage by creating custom installation rules.
Add the ADD_INSTALL_TARGET function to easily create a target to install a specific component.

forward COMPONENT parametert in install instruction

---

header.cmake

Related to new CMake policy 0177 since CMake >= 3.31. See https://cmake.org/cmake/help/latest/policy/CMP0177.html

Add normalization step for install_path

---

doxygen.cmake

through the `DOXYGEN_TAGFILES_FROM_DEPENDENCIES` variable. This should help our docs get correct links to eigen doc.
While here, clean its install config a bit.

Doxygen: allow manual specification of some tagfiles

---

python.cmake

Hi,
This is a breaking change, but I think it is worth it. Looking at our current usage, I can see this standard layout being used everywhere:
- arch: `/usr/lib/python3.13/site-packages/eigenpy/__init__.py`
- brew: `/opt/homebrew/lib/python3.13/site-packages/eigenpy/__init__.py`
- conda: `/opt/conda/lib/python3.12/site-packages/eigenpy/__init__.py`
- nix: `/nix/store/as3k32q45valgjl97sfsz5z1y4ylhfrs-python3-3.13.1-env/lib/python3.13/site-packages/eigenpy/__init__.py`
- pip: `/usr/local/lib/python3.13/site-packages/cmeel.prefix/lib/python3.13/site-packages/eigenpy/__init__.py`
- robotpkg: `/opt/openrobots/lib/python3.10/site-packages/eigenpy/__init__.py`
- ros: `/opt/ros/humble/lib/python3.10/site-packages/eigenpy/__init__.py`
The initial idea for turning this OFF was that when using what …

enable PYTHON_STANDARD_LAYOUT by default

---

ros2.cmake

ref. https://github.com/Gepetto/example-robot-data/pull/261 / https://github.com/stack-of-tasks/pinocchio/pull/2554

install ament files by default

---

doxygen.cmake

- process list as a comma-separated native CMake list (less awkward)
- fix extraneous whitespaces
- always use absolute paths (allows dedupe to work)
- remove custom `REMOVE_DUPLICATES()` function

doxygen.cmake : make tagfiles processing more consistent

---

pixi.py

This fixes updating the `version` key (in `cmake --target release`) when using `[workspace]` instead of `[project]` for the package metadata in pixi's recent versions.
cc @jorisv

pixi.py : support pixi.toml's new [workspace] key

---

uninstall.cmake

HPP makefile is repeatedly calling the `install` target to double-check things, which uninstall everything and reinstall each time.
This is not optimal, so I guess this behavior should provide an opt-out hatch.

add AUTO_UNINSTALL option
