- doxygen/footer.html
- doxygen/header-mathjax.html
- doxygen/header.html
* Enable the tree view to ease navigation
* Enable folding/unfolding of folder on recent version of Doxygen. For older version, this should not cause more trouble than a script file not found, thus ignored, by the browser. But it has not been tested.
* Add footer
* Add missing tags at the end of header.html
> Update header and footer of doxygen

- xacro.cmake
Add a command to generate URDF files from xacro.
> Add xacro.cmake

- pkg-config.cmake
It allows the search of requiered depencies which will not be added to the list of depencies
of the current project.
> Add macro ADD_SEPARATE_DEPENDENCY

- github/update-doxygen-doc.sh
This PR fixes #104 
It accounts for the removal of installdox script in recent versions of doxygen. Instead, the local path to the doc is simply replaced by the URL deduced from the organization name + project name for those in the `GIT_DEPENDENCIES` variable.
> Use a different strategy to repair cross links in doxygen

- ide.cmake
CMake Generator can be either Xcode, Visual Studio, QTCreator, etc.
> [IDE] Add tools to organize files when relying on CMake Generator

- ide.cmake
This may be helpful to avoid long tree unfolding.
> Remove common path from complete path given as input

- doxygen.cmake
> Fix doxygen.cmake (don't setup doxytag when not installing the doc)

- doxygen/Doxyfile.in
> Add quote around DOT_PATH and PERL_PATH to handle spaces in the paths

- xacro.cmake
This macro eases the use of xacro.
- Add variable `XACRO_OPTIONS`
- Add macro `RUN_XACRO`
- Update macro `GENERATE_URDF_FILE`
> [Xacro] Split macro GENERATE_URDF_FILE in two.

- dist.cmake
- distcheck.cmake
- git-archive-all.py
This PR allows to handle the packaging of projects on APPLE systems.
> Improve packaging of projects

- distcheck.cmake
- release.cmake
This follows #148 with minor cleaning.
> Clean export LD_LIBRARY_PATH

- hpp.cmake
because @jmirabel looks tired of me adding those lines in every HPP project ;)
> HPP: provide default PROJECT_ORG & PROJECT_URL

- pkg-config.cmake
> Fix pc file name generation.

- base.cmake
- test.cmake
Properly solved the issue in #225
> fix include(CTest)

- python.cmake
and deprecate PYTHON_INSTALL_BUILD
> PYTHON_INSTALL install only the source, fix #136

- version.cmake
> Fix shallow git repository issues

- config.hh.cmake
This would save lots of boilerplate, and it would provide all of our packages with a uniform interface.
> [config.hh] Add @LIBRARY_NAME@_VERSION_AT_LEAST

- github/update-doxygen-doc.sh
This PR includes the doxytag file in the files uploaded online with the doc. It makes it easier to generate correct cross-links when not everything is built in the same environment
> [doxygen] Upload doxytag file as well

- boost.cmake
- boost/FindBoost.cmake
Solving #259. 
@wxmerkt This PR is for you.
> Add macro to find boost

- package-config.cmake
This solves https://github.com/stack-of-tasks/roscontrol_sot/issues/19
> Remove duplicates in pkg-config dependencies inside Config.cmake.

- doxygen.cmake
> [Doxygen] Fix generation of doxytag by default.

- package-config.cmake
Reverts jrl-umi3218/jrl-cmakemodules#399
> Revert "Fix isssue #398"

- find-external/CppAD/FindCppAD.cmake
- find-external/CppAD/FindCppADCodeGen.cmake
fix https://github.com/stack-of-tasks/pinocchio/issues/1233
> [find-external] Add support for CppAD{,CodeGen}

- find-external/CppAD/Findcppad.cmake
- find-external/CppAD/Findcppadcg.cmake
> Add version checking for cppad and cppadcg. Fix #427

- python.cmake
> Fix documentation of PYTHON_SITELIB

- msvc-specific.cmake
> [msvc] Fix wrong use of CMAKE_CURRENT_LIST_DIR

- version-script.cmake
Also:
- One more fix related to #449
- Rewrite in lowercase
> [version-script] Use check_linker_flag if available

- release.cmake
> [release] Update version in package.xml when running make release

- package-config.cmake
> install: fix file path

- boost.cmake
- python.cmake
Hi, 
Following our recent python adventures, dynamic-graph needs some updates.
While testing this, I also fixed an issue unrelated to dynamic-graph, for boost python 2, as only boost python 3 was covered.
> dynamic-graph

- cxx-standard.cmake
to avoid some boring mails from ROS buildfarm on TSID
> cxx-standard: normal operation → STATUS

- doxygen.cmake
The WARNING option might be too aggressive. 
@nim65s @gergondet What do you think?
> Change message output to STATUS when configuring the doc

- .github/workflows/cmake.yml
- base.cmake
Solves #555.
@wxmerkt is fine for you?
> Add SET_DEFAULT_CMAKE_BUILD_TYPE

- base.cmake
> SET_DEFAULT_CMAKE_BUILD_TYPE: add a message()

- version.cmake
That's even worse than #602, but might actually work
> parse package.xml with regex, fix #601

- python-helpers.cmake
It simplifies the code and get access to the created target
> Add PYTHON_BUILD_GET_TARGET function

- uninstall.cmake
> [uninstall] Fix --config when there is no multi-config generator.

- base.cmake
> Apply CMake >= 3.10 policies

- doxygen.cmake
This lines seems to generate incorrect TAGFILE.
> [doxygen] Fix generation of TAGFILES variable.

- CMakeLists.txt
Hi,
This adds a `CMakeLists.txt` to this project, to allow its installation, and therefore provide an alternative distribution strategy.
With this, one can install the jrl-cmakemodules, and after that use it in another project with:
```cmake
find_package(jrl-cmakemodules REQUIRED CONFIG)
get_property(
JRL_CMAKE_MODULES
TARGET jrl-cmakemodules::jrl-cmakemodules
PROPERTY INTERFACE_INCLUDE_DIRECTORIES)
include("${JRL_CMAKE_MODULES}/base.cmake") # as usual
```
That strategy allows to have only one copy of the jrl-cmakemodules on a setup with potentially dozens of packages using it.
This keeps compatibility with previous distributions methods, so to either (in order):
1. try to use from a `cmake` git submodule
2. try to use from installed project
3. try to use from `FetchContent` and download …
> Add CMakeLists.txt to install this project

- find-external/CHOLMOD/FindCHOLMOD.cmake
Use IMPORTED_IMPLIB instead of IMPORTED_LOCATION
> Fix FindCHOLMOD.cmake on Windows

- .pre-commit-config.yaml
Hi,
I shouldn't have merged #687. I thought the error was transient, but it is not. So let's go back. While here, clean the conf a bit, and reduce autoupdate frequency.
> Pre commit

- find-external/CDD/FindCDD.cmake
- find-external/CLP/FindCLP.cmake
- find-external/CoinUtils/FindCoinUtils.cmake
- find-external/glpk/Findglpk.cmake
> find-external: remove prefix from library names

- .docs/cmake.py
- .docs/conf.py
- .docs/pages/base.rst
- .docs/pages/cmake-packages.rst
- .docs/pages/dependencies.rst
- .docs/pages/internal.rst
- .docs/pages/other.rst
- .docs/pages/projects.rst
- base.cmake
- header.cmake
- version.cmake
Update `cmake.py` and `conf.py`
Three warnings remains:
```
jrl-cmakemodules/.docs/pages/other.rst:32: WARNING: undefined label: 'target-dist'
jrl-cmakemodules/.docs/pages/other.rst:33: WARNING: undefined label: 'target-distcheck'
jrl-cmakemodules/.docs/pages/other.rst:34: WARNING: undefined label: 'target-release'
```
> Fix #748 building jrl-cmake documentation on Ubuntu 24.04 LTS

- ros2.cmake
while here, un-hardcode `share` and use GNUInstallDirs instead
> ros2: install package.xml if it exists

- LICENSE
- package.xml
ref. https://github.com/ros/rosdistro/pull/46843
> Updates for inclusion in rosdistro
